spring:
  application:
    name: pokeservice
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:devdb

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

server:
  port: 8081

logging:
  level:
    root: INFO

pokemon.api:
  base-url: ${POKE_API_URL:https://pokeapi.co/api/v2}
